repos:
- repo: local
  hooks:
  - id: formatter
    name: Ruff Formatter
    entry: ruff format pt_bot/ tasks/ tests/
    language: system
    always_run: true
    pass_filenames: false
  - id: linter
    name: Ruff Linter
    entry: ruff check pt_bot/ tasks/ tests/ --fix
    language: system
    always_run: true
    pass_filenames: false
  - id: unit_tests
    name: Unit tests
    entry: pytest tests/unit/
    language: system
    always_run: true
    pass_filenames: false
