services:
  bot:
    hostname: bot
    container_name: bot
    entrypoint: ["bash", "/app/run_app.sh"]
    build:
      context: .
    env_file:
      - "secrets/.env.prod"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:16.1-alpine
    hostname: db
    container_name: db
    volumes:
      - "db-data:/var/lib/postgresql/data"
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - "secrets/.env.prod"

  redis:
    image: redis:7.2.4
    hostname: redis
    container_name: redis
    expose: 
      - 6379
    command: ["/bin/sh", "-c", "redis-server --requirepass $${REDIS_PASSWORD} --save 60 1 --dir /data"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - "secrets/.env.prod"   
    volumes:
      - redis-data:/data

  prefect-server:
    image: prefecthq/prefect:3-python3.11
    container_name: prefect-server
    entrypoint: ["/opt/prefect/entrypoint.sh", "prefect", "server", "start"]
    env_file:
      - "secrets/.env.prod"
    ports:
      - 4200:4200
    depends_on:
      db:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request; print(urllib.request.urlopen('http://0.0.0.0:4200/api/health').read().decode())\""]
      interval: 10s
      timeout: 5s
      retries: 5

  prefect-worker-pool:
    image: prefecthq/prefect:3-python3.11
    container_name: prefect-worker-pool
    entrypoint: [
      "/opt/prefect/entrypoint.sh", 
      "prefect", "worker", "start", 
      "--pool", "MainPool",
      "--type", "docker", 
      "--base-job-template", "/app/prefect-job-template.json"
    ]
    depends_on:
      prefect-server:
        condition: service_healthy
    environment:
      - EXTRA_PIP_PACKAGES=prefect-docker<0.7 requests<2.32
    env_file:
      - "secrets/.env.prod"
    volumes:
      - "./prefect-job-template.json:/app/prefect-job-template.json"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  redis-data:
  db-data:
