
name: Run tests

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    uses: ./.github/workflows/tests.yml
    with:
      environment: env
    secrets:
      ENV_FILE_CONTENT: ${{ secrets.ENV_FILE_CONTENT }}