on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true
    secrets:
      ENV_FILE_CONTENT:
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install uv
        python -m uv sync --frozen
    - name: Setup .env file
      run: |
        cat <<'EOF' > secrets/.env.prod
          ${{ secrets.ENV_FILE_CONTENT }}
        EOF
    - name: Unit tests
      run: |
        python -m uv run pytest tests/pt_bot/unit/ tests/tasks/unit/